[workspace]
resolver = "3"
members = ["remoter-agent", "remoter-attest", "remoter-auth", "remoter-exec", "remoter-proto"]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"
publish = false
rust-version = "1.94"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
unwrap_used = "deny"

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
