[package]
name = "remoter-exec"
edition.workspace = true
version.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
libc = "0.2.189"
remoter-proto = { version = "0.1.0", path = "../remoter-proto" }
serde_json = "1.0.151"
vt100 = "0.16.2"

[lints]
workspace = true

